const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Persist,
		C3.Behaviors.Pin,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{GroundTileSet: 0},
	{Sólido: 0},
	{Ground: 0},
	{Sprite2: 0},
	{PLAYERHP: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{PLAYER: 0},
	{Teclado: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{Projétil: 0},
	{Sprite4: 0},
	{SKELETONHP: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{PlanoDeFundoEmBlocos: 0},
	{WATER: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Áudio: 0},
	{Sprite9: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{BOTÃOPLAY: 0},
	{Mouse: 0},
	{Toque: 0},
	{Sprite10: 0},
	{SCORE: 0},
	{Âncora: 0},
	{Persistir: 0},
	{Fixar: 0},
	{Score: 0},
	{DestruirForaDoLayout: 0},
	{SLASH2: 0},
	{HP_BAR: 0},
	{Esmaecer: 0},
	{SOBREVIVA: 0},
	{VITÓRIA: 0},
	{Texto: 0}
];

self.InstanceType = {
	GroundTileSet: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	PLAYER: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	WATER: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	BOTÃOPLAY: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Toque: class extends self.IInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	SLASH2: class extends self.ISpriteInstance {},
	HP_BAR: class extends self.ISpriteInstance {},
	SOBREVIVA: class extends self.ITextInstance {},
	VITÓRIA: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {}
}